### PR TITLE
Update recommendation.js

### PR DESCRIPTION
**Pull request by KwabenaAppiah**
- Added the ability to filter films by the average TMDb user rating.
- Removed the option to filter films that are exactly 10/10 as there 
  are no films with this rating on TMDb.

### CODE REVIEW

**Comment by lngchn** [comment]
You deleted the movie poster place holder code that Michael did.

**Comment by KwabenaAppiah** [comment]
I didn't delete it. I believe I pulled from a version before that was added in.

**Comment by lngchn** [comment]
Can you put it back and do pull request again?

**Comment by KwabenaAppiah** [comment]
Okay, I just pulled the latest version of 'recommendation.js' and I resubmitted it with my changes.
Please let me know if you see any other conflicts or issues.

**Pull request closed without merging**
